{{ $tls := fromYaml ( include "aws-secret-injector.gen-certs" . ) }}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: aws-secret-injector
webhooks:
- name: awssecretinjector.rousseau.id.au
  clientConfig:
    service:
      name: aws-secret-injector
      namespace: {{ .Release.Namespace }}
      path: "/mutating-pods"
    caBundle: {{ $tls.caCert }}
  rules:
  - operations: ["CREATE","UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  failurePolicy: Ignore
  admissionReviewVersions: ["v1beta1"]
  timeoutSeconds: 5
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret-injector-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ $tls.clientCert }}
  tls.key: {{ $tls.clientKey }}
